import logging
import ignition.model.lifecycle as lifecycle_model
import ignition.model.failure as failure_model
from ignition.service.framework import Service
from ignition.service.resourcedriver import ResourceDriverHandlerCapability, InvalidRequestError
from kubedriver.location import KubeDeploymentLocation
from kubedriver.kegd.model import OperationStates
from kubedriver.kegd.strategy_files import KegDeploymentStrategyFiles
from .topology import KubernetesAssociatedTopology

logger = logging.getLogger(__name__)

class KubeResourceDriverHandler(Service, ResourceDriverHandlerCapability):

    def __init__(self, resource_driver_properties, kegd_orchestrator, kegd_file_reader, render_context_service, name_manager):
        self.resource_driver_properties = resource_driver_properties
        self.kegd_orchestrator = kegd_orchestrator
        self.kegd_file_reader = kegd_file_reader
        self.render_context_service = render_context_service
        self.name_manager = name_manager

    def execute_lifecycle(self, lifecycle_name, driver_files, system_properties, resource_properties, request_properties, associated_topology, deployment_location):
        """
        Execute a lifecycle transition/operation for a Resource.
        This method should return immediate response of the request being accepted,
        it is expected that the ResourceDriverService will poll get_lifecycle_execution on this driver to determine when the request has completed (or devise your own method).

        :param str lifecycle_name: name of the lifecycle transition/operation to execute
        :param ignition.utils.file.DirectoryTree driver_files: object for navigating the directory intended for this driver from the Resource package. The user should call "remove_all" when the files are no longer needed
        :param ignition.utils.propvaluemap.PropValueMap system_properties: properties generated by LM for this Resource: resourceId, resourceName, requestId, metricKey, resourceManagerId, deploymentLocation, resourceType
        :param ignition.utils.propvaluemap.PropValueMap resource_properties: property values of the Resource
        :param ignition.utils.propvaluemap.PropValueMap request_properties: property values of this request
        :param ignition.model.associated_topology.AssociatedTopology associated_topology: 3rd party resources associated to the Resource, from any previous transition/operation requests
        :param dict deployment_location: the deployment location the Resource is assigned to
        :return: an ignition.model.lifecycle.LifecycleExecuteResponse

        :raises:
            ignition.service.resourcedriver.InvalidDriverFilesError: if the scripts are not valid
            ignition.service.resourcedriver.InvalidRequestError: if the request is invalid e.g. if no script can be found to execute the transition/operation given by lifecycle_name
            ignition.service.resourcedriver.TemporaryResourceDriverError: there is an issue handling this request at this time
            ignition.service.resourcedriver.ResourceDriverError: there was an error handling this request
        """
        try:
            kube_location = self.__translate_location(deployment_location)
            render_context = self.render_context_service.build(system_properties, resource_properties, request_properties, kube_location.to_dict())
            keg_name = self.__generate_keg_name(system_properties)
            kegd_files = KegDeploymentStrategyFiles(driver_files.root_path)
            kegd_strategy = self.kegd_file_reader.read(kegd_files.get_strategy_file(), render_context)
            request_id = self.kegd_orchestrator.apply_kegd_strategy(kube_location, keg_name, kegd_strategy, lifecycle_name, kegd_files, render_context)
            associated_topology = self.__build_associated_topology(keg_name, kube_location)
            return lifecycle_model.LifecycleExecuteResponse(request_id, associated_topology)
        finally:
            keep_files = self.resource_driver_properties.keep_files
            if not keep_files and driver_files is not None:
                try:
                    logger.debug(f'Attempting to remove driver files at {driver_files.root_path}')
                    driver_files.remove_all()
                except Exception as e:
                    logger.exception(f'Encountered an error whilst trying to clear out driver files directory {driver_files.root_path}: {str(e)}')

    def get_lifecycle_execution(self, request_id, deployment_location):
        """
        Retreive the status of a lifecycle transition/operation request

        :param str request_id: identifier of the request to check
        :param dict deployment_location: the deployment location the Resource is assigned to
        :return: an ignition.model.lifecycle.LifecycleExecution
        
        :raises:
            ignition.service.resourcedriver.RequestNotFoundError: if no request with the given request_id exists
            ignition.service.resourcedriver.TemporaryResourceDriverError: there is an issue handling this request at this time, an attempt should be made again at a later time
            ignition.service.resourcedriver.ResourceDriverError: there was an error handling this request
        """
        kube_location = self.__translate_location(deployment_location)
        request_report = self.kegd_orchestrator.get_request_report(kube_location, request_id)
        execution_status = lifecycle_model.STATUS_IN_PROGRESS
        failure_details = None
        outputs = None
        associated_topology = None
        if request_report.state == OperationStates.COMPLETE:
            execution_status = lifecycle_model.STATUS_COMPLETE
        elif request_report.state == OperationStates.FAILED:
            execution_status = lifecycle_model.STATUS_FAILED
            failure_details = failure_model.FailureDetails(failure_model.FAILURE_CODE_INTERNAL_ERROR, description=request_report.error)
        return lifecycle_model.LifecycleExecution(request_id, execution_status, outputs=outputs, failure_details=failure_details, associated_topology=associated_topology)

    def lifecycle_execution_monitoring_complete(self, request_id, deployment_location):
        kube_location = self.__translate_location(deployment_location)
        self.kegd_orchestrator.delete_request_report(kube_location, request_id)

    def find_reference(self, instance_name, driver_files, deployment_location):
        """
        Find a Resource, returning the necessary property output values and internal resources from those instances

        :param str instance_name: name used to filter the Resource to find
        :param ignition.utils.file.DirectoryTree driver_files: object for navigating the directory intended for this driver from the Resource package. The user should call "remove_all" when the files are no longer needed
        :param dict deployment_location: the deployment location to find the instance in
        :return: an ignition.model.references.FindReferenceResponse

        :raises:
            ignition.service.resourcedriver.InvalidDriverFilesError: if the scripts are not valid
            ignition.service.resourcedriver.InvalidRequestError: if the request is invalid e.g. if no script can be found to execute the transition/operation given by lifecycle_name
            ignition.service.resourcedriver.TemporaryResourceDriverError: there is an issue handling this request at this time
            ignition.service.resourcedriver.ResourceDriverError: there was an error handling this request
        """
        pass

    def __translate_location(self, deployment_location_as_dict):
        return KubeDeploymentLocation.from_dict(deployment_location_as_dict)

    def __generate_keg_name(self, system_properties):
        resource_id = system_properties.get('resourceId')
        if resource_id == None:
            raise InvalidRequestError('system properties missing \'resourceId\' value')
        resource_name = system_properties.get('resourceName')
        if resource_name == None:
            raise InvalidRequestError('system properties missing \'resourceName\' value')
        return self.name_manager.safe_label_name_for_resource(resource_id, resource_name, prefix='keg')

    def __build_associated_topology(self, keg_name, kube_location):
        topology = KubernetesAssociatedTopology()
        topology.add_keg_entry(keg_name, kube_location)
        return topology
    
